$primary = rgb(ffb782)
$on_primary = rgb(4f2500)
$primary_container = rgb(6d390a)
$on_primary_container = rgb(ffdcc5)

$secondary = rgb(e4bfa7)
$on_secondary = rgb(422b1a)
$secondary_container = rgb(5b412f)
$on_secondary_container = rgb(ffdcc5)

$tertiary = rgb(c7ca95)
$on_tertiary = rgb(30330b)
$tertiary_container = rgb(464920)
$on_tertiary_container = rgb(e3e6af)

$surface = rgb(19120d)
$surface_container = rgb(261e18)
$surface_container_high = rgb(312822)
$on_surface = rgb(f0dfd6)
$on_surface_variant = rgb(d6c3b7)
$outline = rgb(9f8d83)
$outline_variant = rgb(52443b)

$error = rgb(ffb4ab)
$on_error = rgb(690005)
