gui:
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    selectedLineBgColor:
      - "#313244"
    optionsTextColor:
      - "#89b4fa"
    searchingActiveBorderColor:
      - "#f9e2af"
