return {
    background                      = "{{colors.background.default.hex_stripped}}",
    onBackground                    = "{{colors.on_background.default.hex_stripped}}",
    surface                         = "{{colors.surface.default.hex_stripped}}",
    surfaceContainer                = "{{colors.surface_container.default.hex_stripped}}",
    surfaceContainerHigh            = "{{colors.surface_container_high.default.hex_stripped}}",
    onSurface                       = "{{colors.on_surface.default.hex_stripped}}",
    onSurfaceVariant                = "{{colors.on_surface_variant.default.hex_stripped}}",
    outline                         = "{{colors.outline.default.hex_stripped}}",
    outlineVariant                  = "{{colors.outline_variant.default.hex_stripped}}",
    primary                         = "{{colors.primary.default.hex_stripped}}",
    onPrimary                       = "{{colors.on_primary.default.hex_stripped}}",
    secondary                       = "{{colors.secondary.default.hex_stripped}}",
    onSecondary                     = "{{colors.on_secondary.default.hex_stripped}}",
    tertiary                        = "{{colors.tertiary.default.hex_stripped}}",
    onTertiary                      = "{{colors.on_tertiary.default.hex_stripped}}",
    error                           = "{{colors.error.default.hex_stripped}}",
    onError                         = "{{colors.on_error.default.hex_stripped}}",
    inversePrimary                  = "{{colors.inverse_primary.default.hex_stripped}}",
}
