# Material You dynamic theme for btop (default fallback)

theme[main_bg]="#171118"
theme[main_fg]="#ebdfe9"
theme[title]="#74d7cb"
theme[hi_fg]="#74d7cb"
theme[selected_bg]="#005049"
theme[selected_fg]="#91f4e7"
theme[inactive_fg]="#9b8c9b"
theme[graph_text]="#d2c1d2"
theme[meter_bg]="#3a323a"
theme[proc_misc]="#ecb8ce"

theme[cpu_box]="#4f4350"
theme[mem_box]="#4f4350"
theme[net_box]="#4f4350"
theme[proc_box]="#4f4350"
theme[div_line]="#4f4350"

theme[temp_start]="#74d7cb"
theme[temp_mid]="#e7b7e8"
theme[temp_end]="#ffb4ab"

theme[cpu_start]="#74d7cb"
theme[cpu_mid]="#e7b7e8"
theme[cpu_end]="#ffb4ab"

theme[free_start]="#e7b7e8"
theme[free_mid]="#ecb8ce"
theme[free_end]="#74d7cb"

theme[cached_start]="#ecb8ce"
theme[cached_mid]="#e7b7e8"
theme[cached_end]="#74d7cb"

theme[available_start]="#e7b7e8"
theme[available_mid]="#ecb8ce"
theme[available_end]="#74d7cb"

theme[used_start]="#74d7cb"
theme[used_mid]="#e7b7e8"
theme[used_end]="#ffb4ab"

theme[download_start]="#ecb8ce"
theme[download_mid]="#74d7cb"
theme[download_end]="#e7b7e8"

theme[upload_start]="#e7b7e8"
theme[upload_mid]="#ecb8ce"
theme[upload_end]="#74d7cb"

theme[process_start]="#74d7cb"
theme[process_mid]="#e7b7e8"
theme[process_end]="#ffb4ab"

theme[proc_pause_bg]="#ffb4ab"
theme[proc_follow_bg]="#74d7cb"
theme[proc_banner_bg]="#2f282f"
theme[proc_banner_fg]="#ebdfe9"

theme[followed_bg]="#74d7cb"
theme[followed_fg]="#003732"
