"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$shlvl$jobs$status$fill$cmd_duration$battery$memory_usage$os$sudo$docker_context
$git_branch$git_commit$git_state$git_status$nodejs$dotnet$python$kubernetes
$character"""

palette = "catppuccin_mocha"

[fill]
symbol = " "
style = "cyan"

[directory]
style = "bold fg:base bg:lavender"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
format = "[](lavender)[$symbol$path]($style)[](lavender) "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󱑢 "
"Music" = "󰝚 "
"Pictures" = "󰉏 "
"dotfiles" = "󰒓 "

[character]
success_symbol = "[󰄾](bold blue)"
error_symbol = "[󰄾](bold red)"

[os]
disabled = false
style = "bg:mauve fg:base"
format = "[](mauve)[ $symbol ]($style)[](mauve) "

[os.symbols]
Linux = ""
CachyOS = ""
Arch = "󰣇"
Ubuntu = "󰕈"
Windows = "󰍲"

[shlvl]
disabled = false
symbol = "󰔚 "
style = "bg:sky fg:base"
format = "[](sky)[$symbol$shlvl]($style)[](sky) "
threshold = 2

[jobs]
symbol = " "
style = "bg:peach fg:base"
format = "[](peach)[$symbol$number]($style)[](peach) "

[git_branch]
symbol = " "
style = "bg:base fg:lavender"
truncation_length = 35
truncation_symbol = "…"
format = "[](base)[$symbol$branch]($style)[](base) "

[git_commit]
commit_hash_length = 4
tag_symbol = " "
style = "bg:base fg:subtext1"
format = "[](base)[$symbol$hash]($style)[](base) "

[git_state]
style = "bg:base fg:red"
format = "[](base)[$state($progress_current/$progress_total)]($style)[](base) "

[git_status]
format = "([](dirtypink)[ $staged$modified$deleted$renamed$untracked$stashed$conflicted$ahead_behind](bg:dirtypink)[](dirtypink) )"
style = "bg:dirtypink"

staged     = "[󱅃 ](fg:green bg:dirtypink)"
modified   = "[󰏭 ](fg:yellow bg:dirtypink)"
deleted    = "[󱅂 ](fg:red bg:dirtypink)"
renamed    = "[󰜶 ](fg:blue bg:dirtypink)"
untracked  = "[󰞋 ](fg:red bg:dirtypink)"
stashed    = "[󰼽 ](fg:lavender bg:dirtypink)"
conflicted = "[󰞇 ](fg:red bg:dirtypink)"
ahead      = "[󰶣${count} ](fg:teal bg:dirtypink)"
behind     = "[󰶡${count} ](fg:peach bg:dirtypink)"
diverged   = "[󰶤󰶣${ahead_count}󰶡${behind_count} ](fg:mauve bg:dirtypink)"

[nodejs]
symbol = " "
style = "bg:green fg:base"
format = "[](green)[$symbol($version)]($style)[](green) "

[docker_context]
disabled = false
symbol = " "
style = "bg:blue fg:base"
only_with_files = false
format = "[](blue)[$symbol$context]($style)[](blue) "

[kubernetes]
symbol = "☸ "
style = "bg:blue fg:base"
disabled = false
format = "[](blue)[$symbol$context]($style)[](blue) "

[cmd_duration]
min_time = 500
style = "bg:yellow fg:base"
format = "[](yellow)[󱎫 $duration]($style)[](yellow) "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
format = "[$style](fg:$style)[$symbol$percentage](bg:$style fg:base)[ $style](fg:$style) "

[[battery.display]]
threshold = 20
style = "red"

[[battery.display]]
threshold = 50
style = "yellow"


[memory_usage]
disabled = true
threshold = 75
symbol = "󰍛 "
style = "bg:pink fg:base"
format = "[](pink)[$symbol$ram_pct]($style)[](pink) "

[dotnet]
symbol = "󰪮 "
style = "bg:blue fg:base"
format = "[](blue)[$symbol($version)]($style)[](blue) "

[python]
symbol = " "
style = "bg:yellow fg:base"
format = "[](yellow)[$symbol${pyenv_prefix}($version )($virtualenv)]($style)[](yellow) "

[status]
disabled = false
style = "bg:red fg:base"
symbol = "✘"
format = "[](red)[ $symbol ]($style)[](red) "
map_symbol = true

[sudo]
disabled = false
symbol = "󰞀"
style = "bg:red fg:base"
format = "[](red)[ $symbol ]($style)[](red) "

[palettes.catppuccin_mocha]
# --- background ---
crust = "#11111b"
mantle = "#181825"
base = "#1e1e2e"

overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"

surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"

# --- text ---
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"

# --- accents ---
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"

dirtypink = "#240f33"
