"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$hostname$shlvl$jobs$status$fill$cmd_duration$battery$memory_usage${custom.disk_usage}$os$sudo$docker_context
$git_branch$git_commit$git_state${custom.git_identity}$git_status$nodejs$dotnet$python$kubernetes
$character"""

palette = "catppuccin_mocha"

[fill]
symbol = " "
style = "cyan"

[directory]
style = "bold fg:base bg:lavender"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
format = "[](lavender)[$symbol$path]($style)[](lavender) "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󱑢 "
"Music" = "󰝚 "
"Pictures" = "󰉏 "
"dotfiles" = "󰒓 "

[character]
success_symbol = "[󰄾](bold sky)"
error_symbol = "[󰄾](bold maroon)"

[os]
disabled = false
style = "bg:mauve fg:base"
format = "[](mauve)[ $symbol ]($style)[](mauve) "

[os.symbols]
Linux = ""
CachyOS = ""
Arch = "󰣇"
Ubuntu = "󰕈"
Windows = "󰍲"

[hostname]
ssh_only = true
format = "[](sky)[󰒋 $hostname]($style)[](sky) "
style = "bg:sky fg:base"

[jobs]
symbol = " "
style = "bg:peach fg:base"
format = "[](peach)[$symbol$number]($style)[](peach) "

[git_branch]
symbol = " "
style = "bg:base fg:lavender"
truncation_length = 35
truncation_symbol = "…"
format = "[](base)[$symbol$branch]($style)[](base) "

[git_commit]
commit_hash_length = 4
tag_symbol = " "
style = "bg:base fg:subtext1"
format = "[](base)[$symbol$hash]($style)[](base) "

[git_state]
style = "bg:base fg:maroon"
format = "[](base)[$state($progress_current/$progress_total)]($style)[](base) "

[git_status]
format = "([$staged$modified$deleted$renamed$untracked$stashed$conflicted$ahead_behind](fg:pink))"
style = "fg:pink"
staged     = "[](pink)[staged](bg:pink fg:base)[](pink) "
modified   = "[](pink)[modified](bg:pink fg:base)[](pink) "
deleted    = "[](pink)[deleted](bg:pink fg:base)[](pink) "
renamed    = "[](pink)[renamed](bg:pink fg:base)[](pink) "
untracked  = "[](pink)[untracked](bg:pink fg:base)[](pink) "
stashed    = "[](pink)[stashed](bg:pink fg:base)[](pink) "
conflicted = "[](pink)[conflict](bg:pink fg:base)[](pink) "
ahead      = "[](pink)[󰶣${count}](bg:pink fg:base)[](pink) "
behind     = "[](pink)[󰶡${count}](bg:pink fg:base)[](pink) "
diverged   = "[](pink)[󰶤󰶣${ahead_count}󰶡${behind_count}](bg:pink fg:base)[](pink) "

[nodejs]
symbol = " "
style = "bg:teal fg:base"
format = "[](teal)[$symbol($version)]($style)[](teal) "

[docker_context]
disabled = false
symbol = " "
style = "bg:sky fg:base"
only_with_files = false
format = "[](sky)[$symbol$context]($style)[](sky) "

[kubernetes]
symbol = "☸ "
style = "bg:sky fg:base"
disabled = false
format = "[](sky)[$symbol$context]($style)[](sky) "

[cmd_duration]
min_time = 500
style = "bg:peach fg:base"
format = "[](peach)[󱎫 $duration]($style)[](peach) "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
format = "[$style](fg:$style)[$symbol$percentage](bg:$style fg:base)[ $style](fg:$style) "

[[battery.display]]
threshold = 20
style = "maroon"

[[battery.display]]
threshold = 50
style = "peach"

[memory_usage]
disabled = true
threshold = 75
symbol = "󰍛 "
style = "bg:pink fg:base"
format = "[](pink)[$symbol$ram_pct]($style)[](pink) "

[custom.disk_usage]
command = "usage=$(df $HOME --output=pcent | tail -1 | tr -dc '0-9'); if [ \"$usage\" -gt 85 ]; then echo $usage; fi"
shell = ["sh"]
style = "bg:maroon fg:base"
format = "([](maroon)[󰋊 $output%]($style)[](maroon) )"
when = "true"

[custom.git_identity]
command = "local=$(git config --local user.email); global=$(git config --global user.email); if [ -n \"$local\" ] && [ \"$local\" != \"$global\" ]; then echo \"$local\"; fi"
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
shell = ["sh"]
style = "bg:lavender fg:base"
format = "([](lavender)[ $output]($style)[](lavender) )"

[dotnet]
symbol = "󰪮 "
style = "bg:sky fg:base"
format = "[](sky)[$symbol($version)]($style)[](sky) "

[python]
symbol = " "
style = "bg:rosewater fg:base"
format = "[](rosewater)[$symbol${pyenv_prefix}($version )($virtualenv)]($style)[](rosewater) "

[status]
disabled = false
style = "bg:maroon fg:base"
symbol = "✘"
format = "[](maroon)[ $symbol ]($style)[](maroon) "
map_symbol = true

[sudo]
disabled = false
symbol = "󰞀"
style = "bg:maroon fg:base"
format = "[](maroon)[ $symbol ]($style)[](maroon) "

[palettes.catppuccin_mocha]
# --- background ---
crust = "#11111b"
mantle = "#181825"
base = "#1e1e2e"

overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"

surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"

# --- text ---
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"

# --- accents ---
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"

dirtypink = "#240f33"
