export use catppuccin_mocha.nu *
export use docker.nu *
export use dotnet.nu *
export use git.nu *
export use misc.nu *
export use node.nu *
export use python.nu *
export use ssh.nu *
export use test-speed.nu *
export use yazi.nu *
export use setup_mpv.nu setup-mpv
